"""builder.go_function — /go/ 어필리에이트 리다이렉트 Cloudflare Pages Function 생성 (세션 #22).

`/go/<slug>` → 알리 deeplink 302를 **Pages Function**(functions/go/[[path]].js)으로 처리한다.
별도 Worker(`wrangler deploy`, deny 차단됨) 대신 **정규 Pages 배포(git push → CI)로 함께 배포** —
권한·인프라 단순화. slug→deeplink 맵을 published 상품에서 생성해 함수에 임베드한다
(알리 deeplink가 ~1065자라 Cloudflare `_redirects`의 1000자 제한을 넘어 불가 → 함수 임베드).

go_gateway.js(Worker)와 동작 동등: 미등록 slug → 홈 302(404 X·봇 학습 차단). 단 D1 클릭 로깅은
보류(추후 Pages Function에 D1 바인딩으로 복원 가능). 빌드(`build --full`)마다 재생성되어 DB와 일치.
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path
from typing import Any

from tracker import slug_map

HOMEPAGE_URL = "https://honsallim.com/"


def _function_source(mapping: dict[str, str]) -> str:
    """functions/go/[[path]].js 소스 — slug→deeplink 맵 임베드 + 302 핸들러."""
    map_json = json.dumps(mapping, ensure_ascii=True, separators=(",", ":"))
    return (
        "// AUTO-GENERATED by builder.go_function (세션 #22) — 직접 수정 금지(build 시 재생성).\n"
        "// /go/<slug> → AliExpress 어필리에이트 deeplink 302. 미등록 slug → 홈(404 회피).\n"
        f"const SLUG_MAP = {map_json};\n"
        f'const HOME = "{HOMEPAGE_URL}";\n'
        "export async function onRequest(context) {\n"
        "  const url = new URL(context.request.url);\n"
        '  let slug = (url.pathname.split("/go/")[1] || "");\n'
        '  slug = slug.split("/")[0].split("?")[0];\n'
        "  const dest = SLUG_MAP[slug];\n"
        "  return Response.redirect(dest || HOME, 302);\n"
        "}\n"
    )


def generate_go_function(conn: sqlite3.Connection, project_root: Path) -> dict[str, Any]:
    """published 상품 slug→deeplink로 functions/go/[[path]].js 생성. 반환: {path, count}.

    collect_slug_map_entries(published article·카테고리 연결 상품만)를 재사용 — 미게시 딥링크
    비노출(POLICY §6). 맵이 비면(상품 0) 빈 맵 함수 생성(모든 /go/ → 홈, 안전).
    """
    entries = slug_map.collect_slug_map_entries(conn)
    mapping = {
        e["slug"]: e["deeplink_url"] for e in entries if e.get("slug") and e.get("deeplink_url")
    }
    out = project_root / "functions" / "go" / "[[path]].js"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_function_source(mapping), encoding="utf-8", newline="\n")
    return {"path": str(out), "count": len(mapping)}
